### ISSUE TITLE
problems in running this project

### ISSUE THREAD

**Issue by hitxing** [Aug583/F-COOPER#2]
hello! thanks for provide this project, there are many problems when I running this project  could you please give me more details about how to make this project work? 

(base) xwx@server-bd2:~/deeplearning/projects/F-COOPER/SparseConvNet$ sh develop.sh
running develop
running egg_info
creating sparseconvnet.egg-info
writing sparseconvnet.egg-info/PKG-INFO
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
writing top-level names to sparseconvnet.egg-info/top_level.txt
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    zip_safe=False,
  File "/home/xwx/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/xwx/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/xwx/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/xwx/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/xwx/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/home/xwx/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/xwx/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/xwx/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/xwx/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/home/xwx/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/xwx/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/xwx/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 232, in build_extensions
    self._check_abi()
  File "/home/xwx/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 370, in _check_abi
    check_compiler_abi_compatibility(compiler)
  File "/home/xwx/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 162, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/home/xwx/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 138, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/home/xwx/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/xwx/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
(base) xwx@server-bd2:~/deeplearning/projects/F-COOPER/SparseConvNet$ 

(base) xwx@server-bd2:~/deeplearning/projects/F-COOPER/COOPER$ python create_data.py create_kitti_info_file --data_path=KITTI_DATASET_ROOT
Traceback (most recent call last):
  File "create_data.py", line 9, in <module>
    from second.core import box_np_ops
  File "/home/xwx/deeplearning/projects/F-COOPER/COOPER/second/core/box_np_ops.py", line 5, in <module>
    from spconv.utils import rbbox_iou, rbbox_intersection
ModuleNotFoundError: No module named 'spconv'

**Comment by Jin123learn** [comment]
> hello! thanks for provide this project, there are many problems when I running this project could you please give me more details about how to make this project work?
> 
> (base) xwx@server-bd2:~/deeplearning/projects/F-COOPER/SparseConvNet$ sh develop.sh running develop running egg_info creating sparseconvnet.egg-info writing sparseconvnet.egg-info/PKG-INFO writing dependency_links to sparseconvnet.egg-info/dependency_links.txt writing top-level names to sparseconvnet.egg-info/top_level.txt writing manifest file 'sparseconvnet.egg-info/SOURCES.txt' package init file 'sparseconvnet/SCN/**init**.py' not found (or not a regular file) reading manifest file 'sparseconvnet.egg-info/SOURCES.txt' writing manifest file 'sparseconvnet.egg-info/SOURCES.txt' running build_ext Traceback (most recent call last): File "setup.py", line 39, in zip_safe=False, File "/home/xwx/anaconda3/lib/python3.6/site-packages/setuptools/**init**.py", line 129, in setup return distutils.core.setup(**attrs) File "/home/xwx/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup dist.run_commands() File "/home/xwx/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands self.run_command(cmd) File "/home/xwx/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command cmd_obj.run() File "/home/xwx/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run self.install_for_development() File "/home/xwx/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development self.run_command('build_ext') File "/home/xwx/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command self.distribution.run_command(command) File "/home/xwx/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command cmd_obj.run() File "/home/xwx/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run _build_ext.run(self) File "/home/xwx/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run _build_ext.build_ext.run(self) File "/home/xwx/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run self.build_extensions() File "/home/xwx/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 232, in build_extensions self._check_abi() File "/home/xwx/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 370, in _check_abi check_compiler_abi_compatibility(compiler) File "/home/xwx/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 162, in check_compiler_abi_compatibility if not check_compiler_ok_for_platform(compiler): File "/home/xwx/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 138, in check_compiler_ok_for_platform which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT) File "/home/xwx/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output **kwargs).stdout File "/home/xwx/anaconda3/lib/python3.6/subprocess.py", line 418, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1. (base) xwx@server-bd2:~/deeplearning/projects/F-COOPER/SparseConvNet$
> 
> (base) xwx@server-bd2:~/deeplearning/projects/F-COOPER/COOPER$ python create_data.py create_kitti_info_file --data_path=KITTI_DATASET_ROOT
> Traceback (most recent call last):
> File "create_data.py", line 9, in
> from second.core import box_np_ops
> File "/home/xwx/deeplearning/projects/F-COOPER/COOPER/second/core/box_np_ops.py", line 5, in
> from spconv.utils import rbbox_iou, rbbox_intersection
> ModuleNotFoundError: No module named 'spconv'

is this code complete? does it work?

**Comment by xiaoyucheri** [comment]
i think the code has issues

**Comment by zqzqz** [comment]
https://github.com/traveller59/spconv
