### ISSUE TITLE
KeyError: ‘annos’

### ISSUE THREAD

**Issue by smallzm** [Aug583/F-COOPER#7]
Traceback (most recent call last):
  File "./pytorch/train.py", line 646, in <module>
    fire.Fire()
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 398, in train
    raise e
  File "./pytorch/train.py", line 377, in train
    gt_annos = [
  File "./pytorch/train.py", line 378, in <listcomp>
    info["annos"] for info in eval_dataset.dataset.kitti_infos
KeyError: 'annos'

**Comment by nanaiii349** [comment]
You should use car_new.config instead of car.config as written in README. Because the eval_dataset you want to use in the evaluate should be obtained from kitti_infos_val.pkl, not kitti_infos_test.pkl.
